# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OpenTUNA 开源软件镜像站
school: OpenTUNA
brand: OpenTUNA Open Source Mirror
logo: true
issue_tag: opentuna
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"
url: "https://opentuna.cn"
hostname: "opentuna.cn"
hide_navbar: true
hide_server_status: true
footnote: <img alt="wangan_icon" title="wangan_icon" src="//s3.cn-north-1.amazonaws.com.cn/aws-dam-prod/china/0089205973_1471847044_icon.888cd2e3d7db9c6704dffbf66a752793979f7bf2.png"> 京公网安备 11010802032579号 | 京ICP备20029420号-1

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false


sass:
    sass_dir: static/css

gems:
    - jekyll-babel
    - jekyll-sitemap

babel_js_extensions: 'es6'

exclude: [Gemfile, Gemfile.lock, README.md, gen_robot.sh, vendor, geninfo/, gen_robot.sh, gen_desc.py, Dockerfile*]

# vim: ts=2 sts=2 sw=2 expandtab
